### ISSUE TITLE
Setting custom amount of channels

### ISSUE THREAD

**Issue by FBSANAKONDA** [meowistic/discord-token-nuker#1]
you should give the opportunity to set the amount of channels created, if not in the terminal, then just by editing the code. I would appreciate that feature, or a response like you can st it in line "x" thanks for the code, really good nuker.

**Comment by meowistic** [comment]
Thank you for the suggestion, I will add it in the next 2 hours. Also thank you so much for the compliment, it means a lot to me :) 

You're the first person to use my tools and I got really happy when an issue has been opened knowing someone uses my projects.

**Comment by FBSANAKONDA** [comment]
I have a lot of suggestions, but since I dont know to write in any coding language, I will submit them with a couple of days between, so you have time to think about it or maybe add it to the code

**Comment by meowistic** [comment]
Hello, my life is pretty boring and all i do is sit and code all day, so you can suggest them all at once. I don't really need time to think as i will quickly think whether the suggestion will be useful for other people to use or not.

**Comment by meowistic** [comment]
Successfully added feature and a few code optimizations!
