### ISSUE TITLE
Suggestions 

### ISSUE THREAD

**Issue by FBSANAKONDA** [meowistic/discord-token-nuker#2]
1. 

a)   Make some new commands, like 
!admin <username> - makes the @-d user moderator on the server

b) !troll <ránk name/username/ if left blank everyone> dm-s the selected person/rank/everyone the spam massages it is spamming in the chat 

c) !create <name> creates a new text channel with the name, when dm-d to the bot (Incase they delete the channels, but leave the bot in.)

d) !token pings an user and creates a long randomized text after it, to look like it is their discord token 

e) make a feature, that saves configs in a file, so if you boot the nuker up you can select 1- loads config/if more configs select after 1 or 2

Or 2- make new config

That is for now, good luck

**Comment by FBSANAKONDA** [comment]
Maybe we could have the !create command in the terminal it is running in. The bots accept DM-S, I have used untitlednuker in the DM-S, maybe you should check out how he did it (you can dm the bot !settings or !help and it responds) so I tought you could dm this command, or if it's somehow easy to make I would recommend adding it to every comment. That is for it, bye!![IMG_20230227_215907.jpg](https://user-images.githubusercontent.com/103428287/221684500-326da31c-478a-47bd-8e83-ab2af7f7a107.jpg)

**Comment by FBSANAKONDA** [comment]
So there is a chance discord has a limit for channels without categories, because I set a really big number, and its only generating the same amount as before the update, so maybe you should do like creating a category named NUKED BY <nick> and put 100 channels into it, then make another category named the same and so on

I ofc get this error, beacuse we are nuking a server: Traceback (most recent call last):
  File "/home/myname/.local/lib/python3.11/site-packages/discord/client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "/home/myname/gr/kurvagyors nuker/discord-token-nuker/nuke.py", line 160, in on_guild_channel_create
    await channel.send(r)
  File "/home/myname/.local/lib/python3.11/site-packages/discord/abc.py", line 1538, in send
    data = await state.http.send_message(channel.id, params=params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2023-02-27 22-16-17.mkv.zip](https://github.com/meowistic/discord-token-nuker/files/10844515/2023-02-27.22-16-17.mkv.zip)

  File "/home/myname/.local/lib/python3.11/site-packages/discord/http.py", line 759, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 429 Too Many Requests (error code: 0): You are being rate limited.

So maybe you should try adding in the category thingy I said, but that is what I noticed

since github only supports .zips, I recorded a video and wrapped it, you can watch it if you wanna see what im talking about

**Comment by meowistic** [comment]
Okay ill take that in note. Could you add me on discord by the way? It'd be easier for you to suggest things and I could edit them faster. meowist#1525

I can invite ou to a server with other projects that i edit daily!

**Comment by FBSANAKONDA** [comment]
ohh and one more thing. maybe add a !continue so if I want to continue the nuking not start over
 sur ill add you
